services:
  backend:
    build: 
      context: ./backend
    container_name: landing_backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build: 
      context: ./frontend
    container_name: landing_frontend
    ports:
      - "4000:80" 
    restart: unless-stopped
    depends_on:
      - backend