version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: landing_backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build: 
      context: ./frontend
    container_name: landing_frontend
    # 기존 "3000:80" 에서 "4000:80"으로 변경되었습니다.
    ports:
      - "4000:80" 
    restart: unless-stopped
    depends_on:
      - backend